apiVersion: v1
kind: Service
metadata:
  name: ic-webapp
  labels:
    env: prod
    app: ic-webapp
  namespace: ic-webapp

spec:
  type: NodePort
  selector:
    app: ic-webapp

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
