apiVersion: v1
kind: Service
metadata:
  name: pg-admin
  labels:
    env: prod
    app: pg-admin
  namespace: ic-webapp

spec:
  type: NodePort
  selector:
    app: pg-admin

  ports:
    - protocol: TCP
      port: 5050
      targetPort: 80
      nodePort: 30050
