apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    env: prod
    app: ic-webapp
  namespace: ic-webapp

spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
        
