apiVersion: v1
kind: Service
metadata:
  name: odoo
  labels:
    env: prod
    app: odoo
  namespace: ic-webapp

spec:
  type: NodePort
  selector:
    app: odoo

  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
      nodePort: 30069
